### ISSUE TITLE
api key in git

### ISSUE THREAD

**Issue by pox** [mtthai/sunny#1]
Cool project, Jabroni, but you really shouldn't commit your API keys. Better rotate it.

https://github.com/mtthai/sunny/blob/fac325141d1e21f6cd1b5446f9b58206ca862023/firebase.js#L3

**Comment by mtthai** [comment]
Ah thanks for the heads up. Made it a long time when I was starting out so there might be some weird design choices here. 

Haven't found a way to hide firebase config api keys on front end projects so I'll just rotate them periodically like you suggested. I also added http referrer restrictions so it'll only accept requests from the sunny website.
